apiVersion: finops.b100to.dev/v1alpha1
kind: IdleWindow
metadata:
  labels:
    app.kubernetes.io/name: idle-reaper
    app.kubernetes.io/managed-by: kustomize
  name: idlewindow-sample
spec:
  # TODO(user): Add fields here
