---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - finops.b100to.dev
  resources:
  - idlewindows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - finops.b100to.dev
  resources:
  - idlewindows/finalizers
  verbs:
  - update
- apiGroups:
  - finops.b100to.dev
  resources:
  - idlewindows/status
  verbs:
  - get
  - patch
  - update
